### PR TITLE
Remove common field prefixes when deriving parameter names

### PR DESCRIPTION
**Pull request by mossprescott**
This was always the intention, but I forgot about it until I looked at some large generated records in Haddock.

Given a data type `Foo`, will now remove `_`, `foo`, or `_foo` from each field name, then un-capitalize the remainder to come up with the corresponding type parameter. That matches what `makeLenses` expects, for example, and should work with most code bases. In theory, these parameter names won't always be unique, but probably only in case of unintentional conflict resulting in a compile error.

Because my first commit passed all the tests but was blatantly wrong, also added a very simple test that just uses the field names explicitly. I don't think there's a simple way to verify the names of the type parameters in an automated way.

cc @dfithian

### CODE REVIEW

**Comment by mossprescott** [comment]
The idea is to preserve the field names you wrote, and just to generate nicer-looking type parameter names. Those generated names never actually appear in source code, so they could actually just be `_0`, `_1`, etc. But this way corresponds to what people tend to actually do, and what was already being shown in the comments on the splices.

So, no, your assumption is incorrect. If you write `a :: ...`, you get `a :: a`, and if you write `_fooName :: ...` you get `_fooName :: name`. The actual field/accessor name should always be exactly what you wrote.

**Comment by mossprescott** [comment]
I just discovered an interaction between this change and the other usability fix I did to use "Uninterpolated" type synonyms when they're available. Now I either need to write a parameter-name-independent comparison for types, or more likely just do the same renaming in another spot…

**Comment by dfithian** [comment]
> So, no, your assumption is incorrect. If you write `a :: ...`, you get `a :: a`, and if you write `_fooName :: ...` you get `_fooName :: name`. The actual field/accessor name should always be exactly what you wrote.

Ahh, yes that is very nicely usable.

**Comment by mossprescott** [comment]
Alright I looked into the other problem I found and it's unrelated so I'm writing an issue for it and I think this is ready to go.

**Comment by mossprescott** [comment]
See #14, which I don't think should hold up this PR.

**Pull request merged**
