### PR TITLE
TH for simple records, newtypes, and sums

### LINKED ISSUE #11: Feature request: TH splice for record types
A common pattern is to define a completely parameterized record type, along with aliases for both normal and "uninterpolated" variants:

```haskell
data Foo' = Foo
  { _fooBar :: bar
  , _fooBaz :: baz
  } deriving (Eq, Show, Generic)
type Foo = Foo' Text (Maybe Int)
type UninterpolatedFoo = Foo' (Uninterpolated Text) (Maybe (Uninterpolated Int))
```

It would be great to have a syntax so we could just write the type in a more normal way and get the extra bits "for free":

```haskell
[interpolated|
data Foo = Foo
  { _fooBar :: String
  , _fooBaz :: Maybe Int
  } deriving (Eq, Show, Generic)
|]
```

I _think_ that's a thing that could be done, at least for the common cases.

### PR DESCRIPTION
**Pull request by mossprescott**
Closes #11.

This works for simple, monomorphic records and newtypes, as well as monomorphic sums where each constructor has no more than one argument. 

This isn't the clearest TH ever written. Using the AST constructors and lifted versions in a pretty random way because I've struggled to get this sort of thing to work with quasi-quoting in the past.

If it doesn't recognize the shape of a declaration as something it can handle, it will at least now say so and include the type it didn't like in the error message.

- [x] separately generate the polymorphic declaration and the "Uninterpolated" synonym (so you can define all your types first and then the synonyms, e.g. in case you need to define instances in between)
- [x] handle some simple polymorphic types (e.g. you have some fields with concrete types but one or two are not fixed)
- [x] refer to "Uninterpolated" synonyms rather than their inlined forms when possible.

cc @dfithian @DanBurton @hkailahi @ystael

### CODE REVIEW

**Comment by dfithian** [comment]
Yeah this honestly doesn't look that bad. Quasi quotes would be an improvement but this seems fine too.

**Comment by mossprescott** [comment]
Thanks! If I knew how to make this work with QQ I would, but everything has lists of types in it, so I approach with trepidation. 

Since you don't seem to hate it I'll try using it in client code before going any further. I _think_ this is enough to cover most of our uses.

**Comment by mossprescott** [comment]
After trying this in real code, it seemed to really call for going the next step and handling some other shapes, including `newtype`s and simple sum types. So I added those cases (will push shortly.)

Then I ran into stickier issue, which is how to handle nesting of `UninterpolatedFoo` types. For example, you might have defined `data Foo` as a record, and want to see something like this generated for `UninterpolatedFoo`:

```haskell
type UninterpolatedFoo = Foo'
  (Uninterpolated T.Text)  
  (Maybe (Uninterpolated Int))
  (Uninterpolated Bool))
  [Uninterpolated Bar]  -- probably a newtype with FromTemplateValue
  Baz' (Uninterpolated X) (Uninterpolated Y)  --  probably corresponds to UninterpolatedBaz, if there is such a thing
  (Map Char (Uninterpolated T.Text))
```

There are several decisions being made here about what gets wrapped in `Uninterpolated`, and it's not entirely clear to me that there's enough information available to the generator to figure out where to wrap. On the other hand, if I punt and leave it to the user to write the `UninterpolatedFoo` synonyms by hand, then this splice is still worth something, but it's not such a clear win.

**Comment by mossprescott** [comment]
OK, so I got our codebase to compile with all of the relevant types but one generated by this new stuff. Practically speaking, the way `Uninterpolated` is being injected works out pretty well, with one caveat:

The choice of what to wrap is made based on what `FromTemplateValue` instances are in scope _at the point of the splice_. That means you get different generated types depending on where in the file you put those instances, and in particular if you put them together with other instances after you define all your data types, then the wrong thing is generated. Of course, if you define these types in a separate module, you don't have the problem, and in many cases you might want to do that anyway.

That's certainly an annoying complication, but on the whole I think this is working well enough to be worth including. Of course you can always skip it and define the types yourself if you don't like the trade-offs.

**Comment by mossprescott** [comment]
Phew! I believe the Template Haskell beast has been slain, at least for now. Will test with client code before making another call for review, but modulo any cases that need fixing this is the way I intend it to work.

**Comment by dfithian** [comment]
Maybe add something to the changelog?

**Pull request merged**
